extends Node

const AIR = 0

const RUBY = 1
const TOPAZ = 2
const EMERALD = 3
const SAPPHIRE = 4

const GEMS = [RUBY,TOPAZ,EMERALD,SAPPHIRE]

const RED_DIAMOND = 5
const YELLOW_DIAMOND = 6
const GREEN_DIAMOND = 7
const BLUE_DIAMOND = 8
const RAINBOW_DIAMOND = 9

const DIAMONDS = [RED_DIAMOND,YELLOW_DIAMOND,GREEN_DIAMOND,BLUE_DIAMOND]

const H_DRILL = 10
const V_DRILL = 11
const DRILLS = [H_DRILL,V_DRILL]

const BOMB = 12

var GAME_TOOLS = [H_DRILL,V_DRILL,BOMB] + DIAMONDS

const BRICK = 13

const RED_BRICK = 14
const YELLOW_BRICK = 15
const GREEN_BRICK = 16
const BLUE_BRICK = 17

const BRICKS = [BRICK,RED_BRICK,YELLOW_BRICK,GREEN_BRICK,BLUE_BRICK]
const COLORED_BRICKS = [RED_BRICK,YELLOW_BRICK,GREEN_BRICK,BLUE_BRICK]

const CROSS = 18
